### ISSUE TITLE
About Commits + Requests

### ISSUE THREAD

**Issue by qogusdn1017** [grandkiwi219/grandkiwi219.github.io#1]
## About Commits

Seems you're using only GitHub upload/edits.

I recommend to use [[Git](https://git-scm.com/)] for add/edit things. That way, your repository looks much better. Plus you can easily check what is wrong with your code.

Official document from Git can be checked at [[Here](https://git-scm.com/docs/gittutorial)].

## Request

I really recommend you to seperate this [[File](https://github.com/grandkiwi219/grandkiwi219.github.io/commit/ba576a5c891971e22f6de4237286995f5db0479b)] in a new repository.

That way the repository will be much better look.

## Any contats if you need:

Discord or else.

**Comment by grandkiwi219** [comment]
Cuz I'm using android smart phone, I'm using only this github site

**Comment by qogusdn1017** [comment]
> Cuz I'm using android smart phone, I'm using only this github site

then make a new repository and put the files
or make the new repository private for a while, and change it to public when it's done. (or make a new public repository for one commit lol)

**Comment by grandkiwi219** [comment]
Sorry, but I need test, so I can't use private repository

**Comment by qogusdn1017** [comment]
> Sorry, but I need test, so I can't use private repository

Because of the github sites, I can share a google vm ssh server with you :/

**Comment by qogusdn1017** [comment]
Talked within Discord. Currently there are no more issues. Closing.
